### POST
POST http://localhost:3000/dataAdd
Content-Type: application/json

{
    "name" : "p1",
    "status": "happy"
}

### DELETE
DELETE http://localhost:3000/dataDel

### GET
GET http://localhost:3000/dataGet

{
    "name" : "p1",
    "status": "happy"
}